name: audio
description: "A new Flutter project."
publish_to: 'none'

environment:
  sdk: ^3.5.1
dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  just_audio: ^0.9.13
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/audio
